// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL-Z3mUKpmpX1TUOIKJWXdxahs1aallrc',
    appId: '1:832453718718:web:39bbaaee6677add37124ef',
    messagingSenderId: '832453718718',
    projectId: 'gymtracker-be1df',
    authDomain: 'gymtracker-be1df.firebaseapp.com',
    storageBucket: 'gymtracker-be1df.firebasestorage.app',
    measurementId: 'G-EW3ZC9PTS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1f_8APob9uOQa5-1jSZT2WDswxAkyoM',
    appId: '1:832453718718:android:463de6856aea7be67124ef',
    messagingSenderId: '832453718718',
    projectId: 'gymtracker-be1df',
    storageBucket: 'gymtracker-be1df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRxXwpka4y-oFDluzBgYkJjGEFgqyJjUA',
    appId: '1:832453718718:ios:06164f27273aa6a97124ef',
    messagingSenderId: '832453718718',
    projectId: 'gymtracker-be1df',
    storageBucket: 'gymtracker-be1df.firebasestorage.app',
    iosClientId: '832453718718-96cbfmljejbt5fbch8v2mjs9d55aetah.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRxXwpka4y-oFDluzBgYkJjGEFgqyJjUA',
    appId: '1:832453718718:ios:06164f27273aa6a97124ef',
    messagingSenderId: '832453718718',
    projectId: 'gymtracker-be1df',
    storageBucket: 'gymtracker-be1df.firebasestorage.app',
    iosClientId: '832453718718-96cbfmljejbt5fbch8v2mjs9d55aetah.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL-Z3mUKpmpX1TUOIKJWXdxahs1aallrc',
    appId: '1:832453718718:web:7f68a26e57998f867124ef',
    messagingSenderId: '832453718718',
    projectId: 'gymtracker-be1df',
    authDomain: 'gymtracker-be1df.firebaseapp.com',
    storageBucket: 'gymtracker-be1df.firebasestorage.app',
    measurementId: 'G-LHG475JXKX',
  );
}
